name: CAPA
description: File a corrective action or preventative action (CAPA) report
title: "[CAPA]: "
labels: ["CAPA", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        This form is used to file a corrective action or preventative action (CAPA) report as specified by (CSC-QMS: SOP-0016)[https://github.com/GSTT-CSC/CSC-QMS]
        Please complete the following fields

  - type: dropdown
    id: Type
    attributes:
      label: Type
      description: is this a corrective action or a preventative action?
      options:
        - Corrective action
        - Preventative action

  - type: input
    id: datix
    attributes:
      label: Datix ID
      description: If this CAPA has an associated datix report, please enter the datix ID here.
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: description
      description: Please describe the action
      placeholder: e.g., No contact details provided as part of product information
    validations:
      required: true

  - type: textarea
    id: root_cause
    attributes:
      label: Root cause
      description: Please describe the root cause
      placeholder: e.g., Loss of information during development
    validations:
      required: true

#  - type: input
#    id: date_root_cause_analysis_completed
#    attributes:
#      label: Date root cause analysis completed
#      description: Please describe the root cause
#      placeholder: e.g., Loss of information during development
#    validations:
#      required: true

  - type: textarea
    id: action
    attributes:
      label: Action (Corrective / Preventive)
      description: Describe the required action to take
      placeholder: New product release incl. contact details; update development process
    validations:
      required: true

#  - type: input
#    id: date_actions_defined
#    attributes:
#      label: Date root cause analysis completed
#      description: Please describe the root cause
#      placeholder: e.g., Loss of information during development
#    validations:
#      required: true

  - type: textarea
    id: adverse_implications
    attributes:
      label: Potentially Adverse Implications
      description: Describe any potentially adverse implicatins to the action
      placeholder: Release of product version and process update
    validations:
      required: true

#  - type: textarea
#    id: verification
#    attributes:
#      label: Verification
#      description: By what metrics will verification of action be assessed
#      placeholder: Number of future complaints related to this issue; review of technical information by Notified Body for completeness
#    validations:
#      required: true

#  - type: input
#    id: date_verification
#    attributes:
#      label: Date of verification
#      description: Please describe the root cause
#      placeholder: e.g., Loss of information during development
#    validations:
#      required: true

#  - type: textarea
#    id: effectiveness_evaluation
#    attributes:
#      label: Effectiveness Evaluation
#      description: Evaluation of
#      placeholder: Evaluation of effectiveness of action
#    validations:
#      required: true
